"""The model registry: what can be installed, what is installed, how to install it.

Ollama's stock context (4096) rejects six frames plus our prompt, so every model
is re-created locally with `num_ctx` raised — the same trick `reels-vision` was
built with. Nothing here downloads implicitly: a pull is a command the user runs.
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

import yaml

REGISTRY_FILE = "models.yaml"
MODELFILE_DIR = Path("scripts/modelfiles")


@dataclass
class ModelEntry:
    name: str            # profile name — what `variants` is keyed by
    tag: str             # what ollama pulls
    num_ctx: int = 32768
    vram_gb: float = 0.0
    role: str = ""
    notes: str = ""
    build: str = ""      # the local model name to run; defaults to `name`

    @property
    def built_name(self) -> str:
        return self.build or self.name


def load_registry(path: str | Path = REGISTRY_FILE) -> list[ModelEntry]:
    p = Path(path)
    if not p.exists():
        return []
    data = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
    out = []
    for name, e in (data.get("models") or {}).items():
        out.append(ModelEntry(
            name=name, tag=e.get("tag", ""), num_ctx=int(e.get("num_ctx", 32768)),
            vram_gb=float(e.get("vram_gb", 0) or 0), role=e.get("role", ""),
            notes=(e.get("notes") or "").strip(), build=e.get("build", ""),
        ))
    return out


def installed_models() -> set[str]:
    """Model names ollama already has. Empty when ollama is not running/installed."""
    if not shutil.which("ollama"):
        return set()
    try:
        r = subprocess.run(["ollama", "list"], capture_output=True, text=True, timeout=30,
                           encoding="utf-8", errors="replace")
    except (OSError, subprocess.SubprocessError):
        return set()
    names = set()
    for line in r.stdout.splitlines()[1:]:          # skip the header
        first = line.split()[0] if line.split() else ""
        if not first:
            continue
        names.add(first)
        names.add(first.split(":")[0])              # `foo:latest` also answers to `foo`
    return names


def status(registry: list[ModelEntry] | None = None) -> list[dict]:
    """Registry entries plus whether the built model is present."""
    have = installed_models()
    return [
        {
            "name": e.name, "tag": e.tag, "role": e.role, "vram_gb": e.vram_gb,
            "num_ctx": e.num_ctx, "notes": e.notes,
            "installed": e.built_name in have,
            "base_pulled": e.tag in have or e.tag.split(":")[0] in have,
        }
        for e in (registry if registry is not None else load_registry())
    ]


def write_modelfile(entry: ModelEntry, directory: Path = MODELFILE_DIR) -> Path:
    """A Modelfile that is only the base model plus the context it actually needs."""
    directory.mkdir(parents=True, exist_ok=True)
    p = directory / f"{entry.name}.Modelfile"
    p.write_text(
        f"# generated by `reels-scrap models pull {entry.name}` — do not edit by hand\n"
        f"# {entry.role}: {entry.notes}\n"
        f"FROM {entry.tag}\n"
        f"# six 720px frames + prompt overflow the stock 4096 context\n"
        f"PARAMETER num_ctx {entry.num_ctx}\n",
        encoding="utf-8",
    )
    return p


def _run(cmd: list[str], timeout: float) -> tuple[int, str]:
    # ollama's progress bars carry box-drawing bytes; Windows text mode defaults to
    # cp1252 and a reader thread dies on them mid-pull. Decode as utf-8, replace.
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout,
                       encoding="utf-8", errors="replace")
    return r.returncode, (r.stderr or r.stdout or "").strip()[:400]


def pull(entry: ModelEntry, timeout: float = 7200) -> dict:
    """`ollama pull` the base tag, then `ollama create` it at the wider context.

    Returns a result dict rather than raising, so pulling `all` reports every arm
    instead of stopping at the first bad tag.
    """
    if not shutil.which("ollama"):
        return {"name": entry.name, "ok": False, "error": "ollama not found on PATH"}
    if entry.build:
        # an explicit `build:` means the model was created by hand (reels-vision,
        # the control arm) — rebuilding it would change what the baseline measured
        return {"name": entry.name, "ok": True, "skipped": "pre-built model, left alone"}

    code, out = _run(["ollama", "pull", entry.tag], timeout)
    if code != 0:
        return {"name": entry.name, "ok": False, "error": f"pull {entry.tag}: {out}"}

    mf = write_modelfile(entry)
    code, out = _run(["ollama", "create", entry.name, "-f", str(mf)], timeout)
    if code != 0:
        return {"name": entry.name, "ok": False, "error": f"create {entry.name}: {out}"}
    return {"name": entry.name, "ok": True, "modelfile": str(mf)}


def as_profiles(registry: list[ModelEntry] | None = None,
                base_url: str = "http://127.0.0.1:11434/v1") -> dict[str, dict]:
    """Registry -> profile dicts. `profiles.resolve_profile` reads the registry
    directly, so this is for showing the shape, not for rewriting a config."""
    return {
        e.name: {
            "kind": "local", "model": e.built_name, "base_url": base_url,
            "num_ctx": e.num_ctx, "max_tokens": 1500, "timeout": 300.0,
            "notes": e.role,
        }
        for e in (registry if registry is not None else load_registry())
    }
